target_model: gat
target_hidden_dims: [352, 256]
dataset: Citeseer
train_setting: 1
test_setting: 1
embedding_dim: 128

train_save_root: ../temp_results/model_states/
test_save_root: ../temp_results/model_states/
res_path: ../res/


