
training_model_arches: ["gat"]
training_layer_dims: [128,  256,  384]
training_hidden_layers: [2]
training_repeat: 3

testing_model_arches: ["gcn", "sage"]
testing_layer_dims: [192, 320, 448]
testing_hidden_layers: [1, 3]
testing_repeat: 15

